Add German i18n file.
matsuyoshi30/harbor pull request #78
Opened 2020-11-25 08:16 UTC by mkalus

Added de.toml

2020-11-25 14:56 UTC, matsuyoshi30 requested changes
Thanks for your contribution! I commented on a thing, so please check it.

2020-11-26 18:19 UTC, lomion0815 commented on i18n/de.toml
> +other = "Vorlage"
I set "Theme" in my de.toml ... any translation felt wrong to me ... Theme is commonly used as a technical term.
```
[older]
other = "Älter"
[newer]
other = "Neuer"
[read-more]
other = "Weiterlesen"
[search]
other = "Suchen..."
[powered-by]
other = "Powered By"
[theme]
other = "Theme"
```

2020-12-05 22:21 UTC, mkalus commented on i18n/de.toml
> +other = "Vorlage"
@lomion0815: I agree, "Theme" sounds good.

2020-12-05 22:22 UTC, mkalus commented
Closing pull request and opening new one with corrected translation file...

2020-12-05 22:22 UTC, closed without merging